[package]
name = "custom-js-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_core = "0.385.0"
deno_ast = { version = "0.52.0", features = ["transpiling"] }
deno_error = "0.7.3"
tokio = { version = "1.49.0", features = ["full"] }
wgpu = "28.0.0"
winit = "0.30"
pollster = "0.4"
